version: "3.8"

services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-node
    ports:
      - "18443:18443"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    command: >
      bitcoind
      -regtest=1
      -server=1
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -fallbackfee=0.0002
      -txindex=1
      -listen=1
      -discover=0
      -dnsseed=0
      -dns=0
      -printtoconsole=1
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=bitcoin", "-rpcpassword=bitcoin", "getblockchaininfo"]
      interval: 10s
      timeout: 5s
      retries: 5

  electrs:
    image: getumbrel/electrs:v0.10.7
    container_name: electrs
    depends_on:
      bitcoin:
        condition: service_healthy
    ports:
      - "50001:50001"
      - "4224:4224"
    volumes:
      - /tmp/electrs_config/config.toml:/data/.electrs/config.toml:ro
      - /tmp/electrs_data:/data/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4224/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

  arch-validator:
    image: ghcr.io/arch-network/local_validator:latest
    container_name: arch-validator
    depends_on:
      electrs:
        condition: service_healthy
    ports:
      - "9002:9002"
      - "9003:9003"
    environment:
      - BITCOIN_RPC_URL=http://bitcoin:18443
      - BITCOIN_RPC_USER=bitcoin
      - BITCOIN_RPC_PASS=bitcoin
      - ELECTRS_URL=electrs:50001
      - RUST_BACKTRACE=1
    restart: on-failure

volumes:
  bitcoin_data:
