version: "3.8"

services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-node
    ports:
      - "18443:18443" # RPC port for regtest
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    command: >
      bitcoind
      -regtest=1
      -server=1
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -fallbackfee=0.0002
      -txindex=1
      -listen=1
      -discover=0
      -dnsseed=0
      -dns=0
      -printtoconsole=1

  electrs:
    image: getumbrel/electrs:v0.10.7
    container_name: electrs
    user: "1000:1000" # Run as non-root user to fix permission issues
    depends_on:
      - bitcoin
    ports:
      - "50001:50001" # Electrum protocol port
      - "4224:4224" # Prometheus monitoring port
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin:ro # Mount bitcoin data as read-only
      - electrs_data:/home/user/db # Mount electrs db with write access
    environment:
      # - ELECTRS_NETWORK=regtest
      - ELECTRS_DB_DIR=/home/user/db
      - ELECTRS_DAEMON_RPC_ADDR=bitcoin:18443
      - ELECTRS_DAEMON_P2P_ADDR=bitcoin:18444
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_MONITORING_ADDR=0.0.0.0:4224
      - ELECTRS_DAEMON_RPC_USER=bitcoin
      - ELECTRS_DAEMON_RPC_PASS=bitcoin
      - ELECTRS_SKIP_BLOCK_DOWNLOAD_WAIT=1
      - ELECTRS_DAEMON_DIR=/home/bitcoin/.bitcoin
    restart: on-failure

  arch-validator:
    image: ghcr.io/arch-network/local_validator:latest
    container_name: arch-validator
    ports:
      - "9002:9002" # RPC port
      - "9003:9003" # P2P port
    depends_on:
      - bitcoin
      - electrs
    environment:
      - BITCOIN_RPC_URL=http://bitcoin:18443
      - BITCOIN_RPC_USER=bitcoin
      - BITCOIN_RPC_PASS=bitcoin
      - ELECTRS_URL=electrs:50001
      - RUST_BACKTRACE=1
    restart: on-failure

volumes:
  bitcoin_data:
  electrs_data:
