name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build all dependencies using Turbo before running tests
      - name: Build packages
        run: yarn turbo build

      - name: Build Rust packages
        run: |
          cd programs/arch-program && cargo build --release
          cd ../associated-token-account && cargo build --release
          cd ../token && cargo build --release
          cd ../apl-amm && cargo build --release

      - name: Test Rust packages
        run: |
          cd programs/arch-program && cargo test
          cd ../associated-token-account && cargo test
          cd ../token && cargo test
          cd ../apl-amm && cargo test

      - name: Run sdk tests
        run: cd packages/apl-sdk && yarn test

      - name: Run cli tests
        run: cd packages/apl-cli && yarn test
