name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: archway-turbo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests in container
        run: |
          docker run --rm archway-turbo:latest yarn turbo test

      - name: Copy artifacts from container
        run: |
          container_id=$(docker create archway-turbo:latest)
          docker cp $container_id:/archway-turbo/target/deploy/. ./target/deploy/
          docker rm $container_id

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program-artifacts
          path: target/deploy/*.so
          compression-level: 9 # Maximum compression to reduce upload time
