name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build and test in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            node:18 \
            bash -c "curl --proto '=https' --tlsv1.2 -sSfL https://release.solana.com/stable/install | sh && \
                    export PATH=\"/root/.local/share/solana/install/active_release/bin:$PATH\" && \
                    yarn install && \
                    yarn turbo build && \
                    yarn turbo test"
