name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build all dependencies using Turbo before running tests
      - name: Build packages
        run: yarn turbo build

      - name: Pull Solana CLI Docker Container
        run: docker pull andreaskasper/solana:cli

      - name: Build Rust packages in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            andreaskasper/solana:cli \
            bash -c "cd programs/arch-program && cargo build-sbf && \
                    cd ../associated-token-account && cargo build-sbf && \
                    cd ../token && cargo build-sbf && \
                    cd ../apl-amm && cargo build-sbf"

      - name: Test Rust packages in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            andreaskasper/solana:cli \
            bash -c "cd programs/arch-program && cargo test && \
                    cd ../associated-token-account && cargo test && \
                    cd ../token && cargo test && \
                    cd ../apl-amm && cargo test"

      - name: Run sdk tests
        run: cd packages/apl-sdk && yarn test

      - name: Run cli tests
        run: cd packages/apl-cli && yarn test
